apiVersion: v1
kind: Service
metadata:
  name: webcolor-service
  namespace: arc-exercise
  labels:
    app: webcolor-app
spec:
  selector:
    app: webcolor-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort
